### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by BERENZ** [BERENZ/MapOfPoland#10]
- [ ] update vignette
- [x] standardise column names
- [ ] standardise units names
- [ ] add unit tests
- [ ] add tests for fast_ggmap
- [ ] change name of `fast_ggmap` to more suitable (i.e. `map_poland`)
- [ ] add descriptions for the data
- [ ] use geom_map instead geom_polygon
- [ ] guess adm. level
- [ ] add lau2 with municipalities (code of gmina ends with 4, 5)

TBA
